_wandb:
    value:
        cli_version: 0.19.2
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 50
                - 53
                - 55
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 50
                - 53
                - 55
                - 103
                - 105
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.12.8
            "5": 0.19.2
            "6": 4.48.0
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
