_wandb:
    value:
        cli_version: 0.19.2
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_nll_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_kl_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_acc
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_nll_epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_acc_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_kl_epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_acc_epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 50
                - 53
                - 55
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 50
                - 53
                - 55
                - 103
                - 105
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.12.8
            "5": 0.19.2
            "6": 4.48.0
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
alpha_k:
    value: 0.5
c:
    value: 148.4132
drop_rate:
    value: 0.2
hidden_dim:
    value: 100
input_dim:
    value: 4
lr:
    value: 0.001
n_train:
    value: 7590
output_dim:
    value: 1
pi:
    value: 0.5
prior_initial_sigma:
    value: 1
prior_large_sigma:
    value: 1
sigma_k:
    value: 0.1353
start_year:
    value: 1980
