_wandb:
    value:
        cli_version: 0.19.2
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": val_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_nll
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_kl
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 50
                - 53
                - 55
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 50
                - 53
                - 55
                - 103
                - 105
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.12.8
            "5": 0.19.2
            "6": 4.48.0
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
drop_rate:
    value: 0.1
hidden_dim:
    value: 64
input_dim:
    value: 3203
lr:
    value: 0.001
n_train:
    value: 32463
output_dim:
    value: 6
prior_initial_sigma:
    value: 1
prior_large_sigma:
    value: 1
